FROM debian:bookworm-slim@sha256:98f4b71de414932439ac6ac690d7060df1f27161073c5036a7553723881bffbe
WORKDIR /usr/src

#clang-format, gdb, valgrind
RUN apt-get update \
  && apt-get install -y \
    curl \
    gnupg2 \
  && curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
  && echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" >> /etc/apt/sources.list \
  && echo "deb-src http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y \
    clang-format-18 \
    gdb \
    gdbserver \
    valgrind

ENV PHPIZE_DEPS="autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c"

RUN apt-get update -y \
  && apt-get install -y \
    ${PHPIZE_DEPS} \
    libxml2-dev \
    libsqlite3-dev \
    zlib1g-dev

ARG PHP_VERSION
ENV PHP_URL="https://www.php.net/distributions/php-${PHP_VERSION}.tar.xz"
ENV CFLAGS="-ggdb3"
ENV TEST_PHP_ARGS="-q"

RUN echo "$PHP_URL" \
  && curl -fsSL -o php.tar.xz "$PHP_URL" \
  && tar -xf php.tar.xz \
  && rm php.tar.xz

ARG PHP_CONFIG_OPTS="--enable-debug --with-pear --with-zlib"
RUN cd php-${PHP_VERSION} \
  && ./buildconf \
  && ./configure ${PHP_CONFIG_OPTS} \
  && make -j $(nproc) \
  && make install

RUN apt-get update -y \
  && apt-get install -y \
    less \
    libprotobuf-dev protobuf-compiler \
    libcurl4-openssl-dev curl \
    hyperfine \
    cmake \
    git

RUN cd /tmp \
  && git clone --recurse-submodules -j $(nproc) --depth=1 https://github.com/open-telemetry/opentelemetry-cpp.git \
  && cd opentelemetry-cpp \
  && mkdir build \
  && cd build \
  && cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE  \
    -DWITH_ZIPKIN=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DBUILD_TESTING=OFF \
    -DWITH_OTLP_GRPC=OFF \
    -DWITH_OTLP_HTTP=ON \
    -DWITH_ABSEIL=OFF \
    -DBUILD_SHARED_LIBS=ON \
    .. \
  && cmake --build . -j $(nproc) --target install

WORKDIR /usr/src/myapp
