ARG ALPINE_VERSION=alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
FROM ${ALPINE_VERSION} AS builder
WORKDIR /usr/src

ENV PHPIZE_DEPS="autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c"

RUN apk add --no-cache \
    ${PHPIZE_DEPS} \
    bash \
    ca-certificates \
    curl \
    tar \
    xz

RUN apk add --no-cache \
    bison \
    coreutils \
    curl-dev \
    libxml2-dev \
    linux-headers \
    re2c \
    readline-dev \
    sqlite-dev

ARG PHP_VERSION
ENV PHP_URL="https://github.com/php/php-src/archive/refs/tags/php-${PHP_VERSION}.tar.gz"

ARG PHP_CONFIG_OPTS="--enable-debug --with-pear --with-zlib"
RUN echo "$PHP_URL" && curl -fsSL -o php.tar.gz "$PHP_URL" \
  && cd /usr/src \
  && mkdir php-src \
  && tar -xzf php.tar.gz -C php-src --strip-components=1 \
  && cd php-src \
  && ./buildconf --force \
  && ./configure ${PHP_CONFIG_OPTS} \
  && make -j $(nproc) \
  && make install

RUN apk add --no-cache \
    less \
    protobuf-dev \
    protobuf \
    openssl-dev \
    hyperfine \
    cmake \
    git

RUN cd /tmp \
  && git clone --recurse-submodules -j $(nproc) --depth=1 https://github.com/open-telemetry/opentelemetry-cpp.git \
  && cd opentelemetry-cpp \
  && mkdir build \
  && cd build \
  && cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE  \
    -DWITH_ZIPKIN=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DBUILD_TESTING=OFF \
    -DWITH_OTLP_GRPC=OFF \
    -DWITH_OTLP_HTTP=ON \
    -DWITH_ABSEIL=OFF \
    -DBUILD_SHARED_LIBS=ON \
    .. \
  && cmake --build . -j $(nproc) --target install

WORKDIR /usr/src/myapp
